query getExpenses($username: String!) {
  expensesOfUser(username: $username) {
    username
    expenses {
      id
      date
      quantity
      category
      month
      year
    }
    busyMonths {
      year
      months
    }
  }
}
